name: CI/CD Workflow

on:
  workflow_dispatch:  # Allows manual triggering from GitHub
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run at 2 AM EST daily (convert to UTC: EST + 5 hours)
    - cron: "0 7 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 5: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Step 6: Authenticate Docker with GCR
    - name: Authenticate Docker with GCR
      run: |
        gcloud auth configure-docker gcr.io --quiet

    # Step 7: Build and push Docker image
    - name: Build and push Docker image
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT: 1
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t gcr.io/no2-app/no2-app-service:latest . \
          --push

    # Step 8: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: no2-app 

    # Step 9: Delete Previous Batch Job (if exists)
    - name: Delete Previous Batch Job
      run: |
        gcloud batch jobs delete no2-job --location us-east1 --quiet || echo "No previous job to delete"

    # Step 10: Submit the Batch Job
    - name: Submit Batch Job
      run: |
        gcloud batch jobs submit no2-job \
          --location us-east1 \
          --config batch-job-config.yaml
