name: CI/CD Workflow

on:
  workflow_dispatch:  # Allows manual triggering from GitHub
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Step 5: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: no2-app 
        export_default_credentials: true

    # Step 6: Deploy to Google Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy no2-app-service \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
