name: CI/CD Workflow

on:
  workflow_dispatch:  # Allows manual triggering from GitHub
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run at 2 AM EST daily (convert to UTC: EST + 5 hours)
    - cron: "0 7 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python (if needed for other steps)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Step 4: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: no2-app 
        export_default_credentials: true

    # Step 5: Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t gcr.io/no2-app/no2-app-service:latest . \
          --push

    # Step 6: Submit the Batch Job
    - name: Submit Batch Job
      run: |
        gcloud batch jobs submit no2-job \
          --location us-east1 \
          --config batch-job-config.yaml
